version: "3.9"

services:
  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE="provisioning,kubernetesClientDashboardsFolders,kubernetesDashboards"
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=mailhog:1025
      - GF_SMTP_FROM_ADDRESS=grafana@example.com
      - GF_SMTP_SKIP_VERIFY=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
      - loki
      - mailhog

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki_index:/loki/index
      - ./loki_cache:/loki/cache
      - ./loki_chunks:/loki/chunks
    environment:
      - LOKI_INDEX_DIR=/loki/index
      - LOKI_CACHE_DIR=/loki/cache
      - LOKI_CHUNKS_DIR=/loki/chunks


  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - /var/log:/var/log
      - ./promtail.yml:/etc/promtail/promtail.yml
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  alertmanager_data:
  loki_index:
  loki_cache:
  loki_chunks:
  pg_data:
  es_data:

