apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: yourdb
    user: youruser
    secureJsonData:
      password: yourpassword
    jsonData:
      sslmode: disable

  - name: Elasticsearch
    type: elasticsearch
    url: http://elasticsearch:9200
    jsonData:
      index: "logs-*"
      timeField: "@timestamp"
      esVersion: 8
      interval: "none"
      logLevelField: ""
      logMessageField: ""
    isDefault: false

